CREATE TABLE vehicleparts
(
    vehiclepartid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    serialnumber TEXT,
    partnumber TEXT,
    description TEXT,
    category TEXT,
    vehicleid TEXT,
    installed BOOLEAN
)