CREATE TABLE purchase_orders
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supplier TEXT,
    supplierid TEXT,
    contact TEXT,
    phone TEXT,
    status TEXT,
    currency TEXT,
    netsum NUMERIC,
    tax NUMERIC,
    totalsum NUMERIC
)